#!/bin/bash




openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=MO/L=KH/O=42/OU=student/CN=albaud.42.ch"
cp -R website /var/www/html/
ls /var/www/html
echo "
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    #server_name www.$DOMAIN_NAME $DOMAIN_NAME;
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;" > /etc/nginx/sites-available/default


echo '
    ssl_protocols TLSv1.3;
    root /var/www/html;
    index website/index.html;
    location ~ [^/]\.php(/|$) { 
            try_files $uri =404;
            fastcgi_pass wordpress:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
} ' >>  /etc/nginx/sites-available/default
chmod -R 777 /var/www/html
nginx -g "daemon off;"